### ISSUE TITLE
Not ready for aeson 0.10

### ISSUE THREAD

**Issue by jcristovao** [yesodweb/persistent#465]
Aeson 0.10, while still not released on hackage, will introduce some changes:

https://github.com/bos/aeson/blob/master/changelog.md

And it seems to break persistent-template tests:

    Test suite test: RUNNING...
    
    JSON serialization
      to/from is idempotent FAILED [1]
      decode
    JSON serialization for Entity
      to/from is idempotent FAILED [2]
      decode
    lens operations
    
    Failures:
    
      1) JSON serialization to/from is idempotent
           Falsifiable (after 1 test): 
           Person {personName = "", personAge = Just 0, personAddress = Address {addressStreet = "", addressCity = "", addressZip = Nothing}}
    
      2) JSON serialization for Entity to/from is idempotent
           Falsifiable (after 1 test): 
           Person {personName = "", personAge = Just 0, personAddress = Address {addressStreet = "", addressCity = "", addressZip = Nothing}}
    
    Randomized with seed 934331499

Although the output is not that clear on what is the expected vs what it got...

Note: this is a forward going issue - the new version of aeson is not alllowed by the current cabal file.

**Comment by MaxGabriel** [comment]
I reproduced with this `stack.yaml` file:

```yaml
flags: {}
packages:
- '.'
- location:
    git: https://github.com/bos/aeson.git
    commit: f6006393a663dd1dc391aabf304ef3181fbdead5
extra-deps: ["attoparsec-0.13.0.1"]
resolver: lts-3.0
```
